#!/usr/bin/env bash
# One-command setup on Linux/macOS.  ./scripts/setup.sh
#
# Installs uv if missing, builds the environment from the lockfile, creates
# .env, and proves the whole thing works by running the test suite.
set -euo pipefail

step() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }

step "Checking for uv"
if ! command -v uv >/dev/null 2>&1; then
  echo "uv not found, installing..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
fi
uv --version

step "Building the environment from uv.lock"
# --locked, not --upgrade: the lockfile is the reproducibility guarantee, and a
# setup script that quietly resolves new versions defeats it.
uv sync --locked

step "Configuring .env"
if [ ! -f .env ]; then
  cp .env.example .env
  printf '\033[33mCreated .env -- add your provider key before running the agent.\033[0m\n'
else
  echo ".env already exists, leaving it alone."
fi

step "Verifying the dataset is reproducible"
uv run python -m generator.cli
git diff --quiet -- data/ 2>/dev/null \
  && echo "data/ regenerated byte-identical" \
  || echo "note: data/ differs from the commit (expected only if you changed the config)"

step "Running the test suite"
uv run pytest -q

printf '\n\033[32mReady.\033[0m\n'
cat <<'TXT'

  Start the services (two terminals):
    make erp
    make ui

  Then:
    make demo     the walkthrough
    make evals    score 200 scenarios
    open http://localhost:8001
TXT
